In [1]:
import pandas as pd

In [25]:
df = pd.read_csv('data/bioactivity_data_3class_pIC50.csv')
df

,Unnamed: 0,molecule_chembl_id,canonical_smiles,bioactivity_class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL311039,CC12CCC(C1)C(C)(C)C2NS(=O)(=O)c1ccc(F)cc1,intermediate,311.422,3.3188,1.0,2.0,5.301030
1,1,CHEMBL450926,CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1cccs1,intermediate,299.461,3.2412,1.0,3.0,5.568636
2,2,CHEMBL310242,CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(...,intermediate,311.422,3.3188,1.0,2.0,5.744727
3,3,CHEMBL74874,CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(...,inactive,327.877,3.8331,1.0,2.0,4.958607
4,4,CHEMBL75183,CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(...,inactive,372.328,3.9422,1.0,2.0,5.000000
...,...,...,...,...,...,...,...,...,...
1619,1621,CHEMBL3653692,CC1=NC2(N=C1N)c1cc(Br)ccc1CC21CCC(F)(F)CC1,active,382.252,4.1854,1.0,3.0,6.399027
1620,1622,CHEMBL3653693,CC1=NC2(N=C1N)c1cc(-c3cncc(Cl)c3)ccc1CC21CCC(F...,intermediate,414.887,5.1383,1.0,4.0,7.275724
1621,1623,CHEMBL3653693,CC1=NC2(N=C1N)c1cc(-c3cncc(Cl)c3)ccc1CC21CCC(F...,intermediate,414.887,5.1383,1.0,4.0,6.962574
1622,1624,CHEMBL3653694,CC1=NC2(N=C1N)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1CC21...,active,457.912,4.7236,2.0,5.0,6.389340
1623,1625,CHEMBL3653694,CC1=NC2(N=C1N)c1cc(NC(=O)c3ccc(Cl)cn3)ccc1CC21...,active,457.912,4.7236,2.0,5.0,7.050610

In [26]:
df2 = df[['canonical_smiles', 'molecule_chembl_id']]
df2.to_csv('data/molecule.smi', sep='\t', index=False, header=False)

In [27]:
! cat data/molecule.smi | head -5

CC12CCC(C1)C(C)(C)C2NS(=O)(=O)c1ccc(F)cc1	CHEMBL311039
CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1cccs1	CHEMBL450926
CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(F)cc1	CHEMBL310242
CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(Cl)cc1	CHEMBL74874
CC12CC[C@@H](C1)C(C)(C)[C@@H]2NS(=O)(=O)c1ccc(Br)cc1	CHEMBL75183

In [28]:
! cat data/molecule.smi | wc -l

    1624

In [29]:
from padelpy import from_smiles

smiles_list = df2['canonical_smiles'].tolist()
fingerprints = from_smiles(smiles_list, fingerprints=True, descriptors=False, output_csv='data/descriptors_output.csv', timeout=None)

### Prepare X and Y Data Matrices

#### X Matrix

In [30]:
X = pd.read_csv('data/descriptors_output.csv')
X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_20260410152023305506255901802_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_20260410152023305506255901802_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_20260410152023305506255901802_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_20260410152023305506255901802_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_20260410152023305506255901802_5,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,AUTOGEN_20260410152023305506255901802_1620,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1620,AUTOGEN_20260410152023305506255901802_1621,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1621,AUTOGEN_20260410152023305506255901802_1622,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1622,AUTOGEN_20260410152023305506255901802_1623,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1623,AUTOGEN_20260410152023305506255901802_1624,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Drop name column

In [31]:
X = X.drop(columns=['Name'])
X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1620,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1621,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1622,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1623,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

#### Y variable

In [34]:
y = df['pIC50']
y

0       5.301030
1       5.568636
2       5.744727
3       4.958607
4       5.000000
          ...
1619    6.399027
1620    7.275724
1621    6.962574
1622    6.389340
1623    7.050610
Name: pIC50, Length: 1624, dtype: float64

#### Combine X and Y

In [35]:
dataset_final = pd.concat([X, y], axis=1)
dataset_final

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.301030
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.568636
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.744727
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.958607
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.399027
1620,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.275724
1621,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.962574
1622,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.389340
1623,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.050610