In [ ]:
# pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 8.2 MB/s eta 0:00:00
Collecting easydict (from chembl_webresource_client)
  Downloading easydict-1.13-py3-none-any.whl (6.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (24.3.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.3.7)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Collecting attrs>=21.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.14.0 in /Users/ryanhobbib/anaconda3/lib/python3.11/site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Installing collected packages: easydict, url-normalize, attrs, cattrs, requests-cache, chembl_webresource_client
  Attempting uninstall: attrs
    Found existing installation: attrs 24.3.0
    Uninstalling attrs-24.3.0:
      Successfully uninstalled attrs-24.3.0
Successfully installed attrs-26.1.0 cattrs-26.1.0 chembl_webresource_client-0.10.9 easydict-1.13 requests-cache-1.3.1 url-normalize-2.2.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

Search for Target Protein

In [3]:
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,15.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,15.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,15.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,15.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,10.0,False,CHEMBL4296578,[],ORGANISM,1335626
8,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
9,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
10,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,3.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
11,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon-SARS-Cov-2 polyprotein,3.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
12,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,3.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

Select and retrieve bioactivity data for Replicase polyprotein 1a

In [4]:
selected_target = targets.target_chembl_id[8]
selected_target

'CHEMBL3927'

In [5]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

IC50 = Concentration to elicit 50% inhibition of target protein

In [6]:
df = pd.DataFrame.from_dict(res)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992021,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,52.0
257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992022,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,30.0
258,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992023,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,14.0
259,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992024,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,48.0
260,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992025,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,20.0

In [7]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5

In [ ]:
# Save to csv
df.to_csv('bioactivity_data.csv', index=False)

In [10]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '18.28', 'le': '0.33', 'lle': '3.25', 'sei': '5.90'}",CHEMBL187579,,CHEMBL187579,5.14,0,http://www.openphacts.org/units/Nanomolar,384103,=,1,1,=,,IC50,nM,,7200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,7.2
,,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '12.10', 'le': '0.33', 'lle': '1.22', 'sei': '13.45'}",CHEMBL188487,,CHEMBL188487,5.03,0,http://www.openphacts.org/units/Nanomolar,383984,=,1,1,=,,IC50,nM,,9400.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,9.4
,,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease) at 20 uM,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '11.56', 'le': '0.29', 'lle': '2.21', 'sei': '8.72'}",CHEMBL185698,,CHEMBL185698,4.87,0,http://www.openphacts.org/units/Nanomolar,384106,=,1,1,=,,IC50,nM,,13500.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.5
,,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.64', 'le': '0.32', 'lle': '1.25', 'sei': '13.06'}",CHEMBL426082,,CHEMBL426082,4.88,0,http://www.openphacts.org/units/Nanomolar,384075,=,1,1,=,,IC50,nM,,13110.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.11
,,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.84', 'le': '0.32', 'lle': '2.16', 'sei': '7.08'}",CHEMBL187717,,CHEMBL187717,5.70,0,http://www.openphacts.org/units/Nanomolar,384234,=,1,1,=,,IC50,nM,,2000.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,2.0
,,1481068,[],CHEMBL828143,In vitro inhibitory concentration SARS coronavirus main protease (SARS CoV 3C-like protease) ,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.14', 'le': '0.37', 'lle': '1.62', 'sei': '16.07'}",CHEMBL365134,,CHEMBL365134,6.01,0,http://www.openphacts.org/units/Nanomolar,384081,=,1,1,=,,IC50,nM,,980.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.98
,,1481088,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(F)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '17.08', 'le': '0.33', 'lle': '1.55', 'sei': '14.22'}",CHEMBL187598,,CHEMBL187598,5.32,0,http://www.openphacts.org/units/Nanomolar,384303,=,1,1,=,,IC50,nM,,4820.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,4.82
,,1481089,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '14.36', 'le': '0.37', 'lle': '1.78', 'sei': '16.11'}",CHEMBL190743,,CHEMBL190743,6.02,0,http://www.openphacts.org/units/Nanomolar,384329,=,1,1,=,,IC50,nM,,950.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.95
,,1481093,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2cccc(Cl)c21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '15.10', 'le': '0.31', 'lle': '0.67', 'sei': '13.24'}",CHEMBL365469,,CHEMBL365469,4.95,0,http://www.openphacts.org/units/Nanomolar,384283,=,1,1,=,,IC50,nM,,11200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,11.2

Handle missing data

In [11]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992021,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,52.0
257,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992022,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,30.0
258,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992023,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,14.0
259,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992024,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,48.0
260,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992025,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,20.0

Data pre-processing

In [12]:
# Label compounds as either active, inactive, or intermediate
bioactivity_class = []
for i in df2.standard_value:
    if float(i) >= 10000:
        bioactivity_class.append("inactive")
    elif float(i) <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

In [54]:
df3 = df2[["molecule_chembl_id", "canonical_smiles", "standard_value"]]
df4 = df3.join(pd.Series(bioactivity_class, name="bioactivity_class"), how='inner')
df4

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL187579,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL188487,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL185698,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive
3,CHEMBL426082,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive
4,CHEMBL187717,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate
...,...,...,...,...
254,CHEMBL2311740,CC(C)(C)NC(=O)[C@@H](c1cccnc1)N(C(=O)c1ccco1)c...,1500.0,active
255,CHEMBL5563508,C=CC(=O)N[C@H](CC(=C)C)C(=O)N1C[C@@H](C(=O)N[C...,3500.0,active
256,CHEMBL5595277,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,52.0,active
257,CHEMBL5570210,CC(C)c1ccc(F)c2[nH]c(C(=O)N3C[C@H]4[C@@H]([C@H...,30.0,active
258,CHEMBL5565685,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,14.0,active

In [57]:
df4.to_csv('data/bioactivity_preprocessed_data.csv', index=False)